/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.entity;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Dialog implements org.apache.thrift.TBase<Dialog, Dialog._Fields>, java.io.Serializable, Cloneable, Comparable<Dialog> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Dialog");

  private static final org.apache.thrift.protocol.TField PARTNER_FIELD_DESC = new org.apache.thrift.protocol.TField("partner", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField LAST_MESSAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("lastMessage", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DialogStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DialogTupleSchemeFactory());
  }

  public User partner; // required
  public Message lastMessage; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PARTNER((short)1, "partner"),
    LAST_MESSAGE((short)2, "lastMessage");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PARTNER
          return PARTNER;
        case 2: // LAST_MESSAGE
          return LAST_MESSAGE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PARTNER, new org.apache.thrift.meta_data.FieldMetaData("partner", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, User.class)));
    tmpMap.put(_Fields.LAST_MESSAGE, new org.apache.thrift.meta_data.FieldMetaData("lastMessage", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Message.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Dialog.class, metaDataMap);
  }

  public Dialog() {
  }

  public Dialog(
    User partner,
    Message lastMessage)
  {
    this();
    this.partner = partner;
    this.lastMessage = lastMessage;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Dialog(Dialog other) {
    if (other.isSetPartner()) {
      this.partner = new User(other.partner);
    }
    if (other.isSetLastMessage()) {
      this.lastMessage = new Message(other.lastMessage);
    }
  }

  public Dialog deepCopy() {
    return new Dialog(this);
  }

  @Override
  public void clear() {
    this.partner = null;
    this.lastMessage = null;
  }

  public User getPartner() {
    return this.partner;
  }

  public Dialog setPartner(User partner) {
    this.partner = partner;
    return this;
  }

  public void unsetPartner() {
    this.partner = null;
  }

  /** Returns true if field partner is set (has been assigned a value) and false otherwise */
  public boolean isSetPartner() {
    return this.partner != null;
  }

  public void setPartnerIsSet(boolean value) {
    if (!value) {
      this.partner = null;
    }
  }

  public Message getLastMessage() {
    return this.lastMessage;
  }

  public Dialog setLastMessage(Message lastMessage) {
    this.lastMessage = lastMessage;
    return this;
  }

  public void unsetLastMessage() {
    this.lastMessage = null;
  }

  /** Returns true if field lastMessage is set (has been assigned a value) and false otherwise */
  public boolean isSetLastMessage() {
    return this.lastMessage != null;
  }

  public void setLastMessageIsSet(boolean value) {
    if (!value) {
      this.lastMessage = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PARTNER:
      if (value == null) {
        unsetPartner();
      } else {
        setPartner((User)value);
      }
      break;

    case LAST_MESSAGE:
      if (value == null) {
        unsetLastMessage();
      } else {
        setLastMessage((Message)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PARTNER:
      return getPartner();

    case LAST_MESSAGE:
      return getLastMessage();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PARTNER:
      return isSetPartner();
    case LAST_MESSAGE:
      return isSetLastMessage();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Dialog)
      return this.equals((Dialog)that);
    return false;
  }

  public boolean equals(Dialog that) {
    if (that == null)
      return false;

    boolean this_present_partner = true && this.isSetPartner();
    boolean that_present_partner = true && that.isSetPartner();
    if (this_present_partner || that_present_partner) {
      if (!(this_present_partner && that_present_partner))
        return false;
      if (!this.partner.equals(that.partner))
        return false;
    }

    boolean this_present_lastMessage = true && this.isSetLastMessage();
    boolean that_present_lastMessage = true && that.isSetLastMessage();
    if (this_present_lastMessage || that_present_lastMessage) {
      if (!(this_present_lastMessage && that_present_lastMessage))
        return false;
      if (!this.lastMessage.equals(that.lastMessage))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(Dialog other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPartner()).compareTo(other.isSetPartner());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPartner()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.partner, other.partner);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastMessage()).compareTo(other.isSetLastMessage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastMessage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastMessage, other.lastMessage);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Dialog(");
    boolean first = true;

    sb.append("partner:");
    if (this.partner == null) {
      sb.append("null");
    } else {
      sb.append(this.partner);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastMessage:");
    if (this.lastMessage == null) {
      sb.append("null");
    } else {
      sb.append(this.lastMessage);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (partner != null) {
      partner.validate();
    }
    if (lastMessage != null) {
      lastMessage.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DialogStandardSchemeFactory implements SchemeFactory {
    public DialogStandardScheme getScheme() {
      return new DialogStandardScheme();
    }
  }

  private static class DialogStandardScheme extends StandardScheme<Dialog> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Dialog struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PARTNER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.partner = new User();
              struct.partner.read(iprot);
              struct.setPartnerIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // LAST_MESSAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.lastMessage = new Message();
              struct.lastMessage.read(iprot);
              struct.setLastMessageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Dialog struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.partner != null) {
        oprot.writeFieldBegin(PARTNER_FIELD_DESC);
        struct.partner.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.lastMessage != null) {
        oprot.writeFieldBegin(LAST_MESSAGE_FIELD_DESC);
        struct.lastMessage.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DialogTupleSchemeFactory implements SchemeFactory {
    public DialogTupleScheme getScheme() {
      return new DialogTupleScheme();
    }
  }

  private static class DialogTupleScheme extends TupleScheme<Dialog> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Dialog struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPartner()) {
        optionals.set(0);
      }
      if (struct.isSetLastMessage()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPartner()) {
        struct.partner.write(oprot);
      }
      if (struct.isSetLastMessage()) {
        struct.lastMessage.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Dialog struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.partner = new User();
        struct.partner.read(iprot);
        struct.setPartnerIsSet(true);
      }
      if (incoming.get(1)) {
        struct.lastMessage = new Message();
        struct.lastMessage.read(iprot);
        struct.setLastMessageIsSet(true);
      }
    }
  }

}

