/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.entity;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ErrorType implements org.apache.thrift.TEnum {
  NO_SUCH_USER(404),
  USER_ALREADY_EXISTS(401),
  INVALID_DATA(400);

  private final int value;

  private ErrorType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ErrorType findByValue(int value) { 
    switch (value) {
      case 404:
        return NO_SUCH_USER;
      case 401:
        return USER_ALREADY_EXISTS;
      case 400:
        return INVALID_DATA;
      default:
        return null;
    }
  }
}
